env:
  global:
    secure: JAvT9KOK4OFtb3CXd5rQiKv0uWaP52b59xTWAzI7Qt34L9qOgzxqojChxmG4I+N8K2wZXsdV53mnw6pJERl/ka34EhFqvLeuoGnzUah1XND4mUdFCIYadE3NlB87TOUHUKcGELXMQGHveD5yVOgijBf6Ouiv/jeiFijSY5XxbtO81IeLsRXjHaxRrF9sN2Oy12wJL8nbXkEKuFzpVZv/tes5hFUsBzKEtQDez3kyV2P+/BECKZdctNHtNNIiSPXXT+7roENMENlF0AERyxmuGGNEOw8IhA0MWQ8G7tWEwNKwMOquFr9OjgLHXGS0nr3GgBF4jtOy7ewqez2bI1IL51TWxhxfxAiOcU2yfc6FJ/DD3IxQq/M1hdL9k+FCA1/sTBc1Ws5FNyaqhgB9iEC9ymscer2HmSK6qDPnfppyo72+UDMxh4uP2DuXSB1xbBPpK2kHNUXqDfI4bcL6+VpOPxSjGqn2Okyv4Crr+dfUI1yNYtPUlz29oO3e/lfCb7dx3mDp4ZPZX8Sw51umoXa9c0LytF/lTxLItRs9d08kNwFEwW5eg1ztP0qDIsGHgNEQ30ICgR5kaq/+DbA5qURl5Nzz0v1lc1etmufdDSF7upF+kf9LujncHG/qfZLz49UDUZqDlb0D33i7+Sn7QpaBTCxqd4T9AkPDcnx4xzbWTts= # GITHUB_TOKEN

language: node_js

cache:
  yarn: true

node_js:
  - '8'

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: build
